import type { Ticket } from "./types"

export const mockTickets: Ticket[] = [
  {
    id: "1",
    filtra: "2024",
    refMoviment: "ENT-001-2024",
    titular: "Marta Puig i Soler",
    concepte: "Entrada Festa Infantil",
    tipus: "Infantil",
    dataEmissio: "2024-05-15",
    dataVenciment: "2024-06-21",
    formaPagament: "Targeta",
    import: 15.00,
    pendent: 0,
    estat: "Pagat",
    entregada: true,
  },
  {
    id: "2",
    filtra: "2024",
    refMoviment: "ENT-002-2024",
    titular: "Joan Garcia i Martí",
    concepte: "Menú Adult",
    tipus: "Adult",
    dataEmissio: "2024-05-16",
    dataVenciment: "2024-06-21",
    formaPagament: "Transferència",
    import: 25.00,
    pendent: 0,
    estat: "Pagat",
    entregada: false,
  },
  {
    id: "3",
    filtra: "2024",
    refMoviment: "ENT-003-2024",
    titular: "Anna Roca i Vidal",
    concepte: "Pack Familiar (2 Adults + 2 Infants)",
    tipus: "Familiar",
    dataEmissio: "2024-05-17",
    dataVenciment: "2024-06-21",
    formaPagament: "Efectiu",
    import: 65.00,
    pendent: 0,
    estat: "Pagat",
    entregada: true,
  },
  {
    id: "4",
    filtra: "2024",
    refMoviment: "ENT-004-2024",
    titular: "Pere Mas i Fontana",
    concepte: "Entrada Festa Infantil",
    tipus: "Infantil",
    dataEmissio: "2024-05-18",
    dataVenciment: "2024-06-21",
    formaPagament: "Targeta",
    import: 15.00,
    pendent: 15.00,
    estat: "Pendent",
    entregada: false,
  },
  {
    id: "5",
    filtra: "2024",
    refMoviment: "ENT-005-2024",
    titular: "Laia Ferrer i Costa",
    concepte: "Menú Adult",
    tipus: "Adult",
    dataEmissio: "2024-05-19",
    dataVenciment: "2024-06-21",
    formaPagament: "Bizum",
    import: 25.00,
    pendent: 0,
    estat: "Pagat",
    entregada: false,
  },
  {
    id: "6",
    filtra: "2024",
    refMoviment: "ENT-006-2024",
    titular: "Marc Serra i Pujol",
    concepte: "Entrada Festa Infantil + Berenar",
    tipus: "Infantil",
    dataEmissio: "2024-05-20",
    dataVenciment: "2024-06-21",
    formaPagament: "Targeta",
    import: 20.00,
    pendent: 0,
    estat: "Pagat",
    entregada: true,
  },
  {
    id: "7",
    filtra: "2024",
    refMoviment: "ENT-007-2024",
    titular: "Núria Bosch i Sala",
    concepte: "Pack Familiar (2 Adults + 3 Infants)",
    tipus: "Familiar",
    dataEmissio: "2024-05-21",
    dataVenciment: "2024-06-21",
    formaPagament: "Transferència",
    import: 75.00,
    pendent: 0,
    estat: "Pagat",
    entregada: false,
  },
  {
    id: "8",
    filtra: "2024",
    refMoviment: "ENT-008-2024",
    titular: "Oriol Camps i Lluch",
    concepte: "Menú Adult",
    tipus: "Adult",
    dataEmissio: "2024-05-22",
    dataVenciment: "2024-06-21",
    formaPagament: "Efectiu",
    import: 25.00,
    pendent: 25.00,
    estat: "Pendent",
    entregada: false,
  },
  {
    id: "9",
    filtra: "2024",
    refMoviment: "ENT-009-2024",
    titular: "Carla Prat i Morera",
    concepte: "Entrada Festa Infantil",
    tipus: "Infantil",
    dataEmissio: "2024-05-23",
    dataVenciment: "2024-06-21",
    formaPagament: "Bizum",
    import: 15.00,
    pendent: 0,
    estat: "Pagat",
    entregada: true,
  },
  {
    id: "10",
    filtra: "2024",
    refMoviment: "ENT-010-2024",
    titular: "David Rovira i Benet",
    concepte: "Menú Adult + Beguda",
    tipus: "Adult",
    dataEmissio: "2024-05-24",
    dataVenciment: "2024-06-21",
    formaPagament: "Targeta",
    import: 30.00,
    pendent: 0,
    estat: "Pagat",
    entregada: false,
  },
  {
    id: "11",
    filtra: "2024",
    refMoviment: "ENT-011-2024",
    titular: "Elena Ribas i Arnau",
    concepte: "Pack Familiar (2 Adults + 1 Infant)",
    tipus: "Familiar",
    dataEmissio: "2024-05-25",
    dataVenciment: "2024-06-21",
    formaPagament: "Transferència",
    import: 55.00,
    pendent: 0,
    estat: "Pagat",
    entregada: true,
  },
  {
    id: "12",
    filtra: "2024",
    refMoviment: "ENT-012-2024",
    titular: "Francesc Vila i Reig",
    concepte: "Entrada Festa Infantil",
    tipus: "Infantil",
    dataEmissio: "2024-05-26",
    dataVenciment: "2024-06-21",
    formaPagament: "Efectiu",
    import: 15.00,
    pendent: 0,
    estat: "Pagat",
    entregada: false,
  },
  {
    id: "13",
    filtra: "2024",
    refMoviment: "ENT-013-2024",
    titular: "Gemma Torrent i Casas",
    concepte: "Menú Adult",
    tipus: "Adult",
    dataEmissio: "2024-05-27",
    dataVenciment: "2024-06-21",
    formaPagament: "Bizum",
    import: 25.00,
    pendent: 25.00,
    estat: "Pendent",
    entregada: false,
  },
  {
    id: "14",
    filtra: "2024",
    refMoviment: "ENT-014-2024",
    titular: "Héctor Domingo i Grau",
    concepte: "Pack Familiar (2 Adults + 2 Infants)",
    tipus: "Familiar",
    dataEmissio: "2024-05-28",
    dataVenciment: "2024-06-21",
    formaPagament: "Targeta",
    import: 65.00,
    pendent: 0,
    estat: "Pagat",
    entregada: true,
  },
  {
    id: "15",
    filtra: "2024",
    refMoviment: "ENT-015-2024",
    titular: "Irene Solé i Batlle",
    concepte: "Entrada Festa Infantil + Berenar",
    tipus: "Infantil",
    dataEmissio: "2024-05-29",
    dataVenciment: "2024-06-21",
    formaPagament: "Transferència",
    import: 20.00,
    pendent: 0,
    estat: "Pagat",
    entregada: false,
  },
]
